system:
  gpu_id: "0"
  use_processes: True
  dask_workers: 6
  dask_threads: 4

paths:
  input_root: "/home/jeongeun.baek/workspace/ws_test/data/20250716T094707_20250716_GCExp4_GC09_IF/Image/Well0001"
  output_root: "outputs/Well0001/mist"
  final_filename: "final_result.zarr"
  bioformats_path: "./bioformats2raw-0.7.0/bin/bioformats2raw"

preprocess:
  rows: 4
  cols: 3
  overlap_pct: 0.1
  search_px: 200
  use_flat_field: True

algorithm:
  psf_sigma: 2.0
  iterations: 20 # 0이면 Deconvolution 안함
  pad_width: 32
  